load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "file_handler",
    srcs = ["file_handler.cpp"],
    hdrs = ["file_handler.h"],
    visibility = ["//visibility:public"]
)