load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "vhdx_handler",
    srcs = ["vhdx_handler.cpp"],
    hdrs = ["vhdx_handler.h"],
    visibility = ["//visibility:public"]
)