load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "linux_virtdisk_handler",
    srcs = ["linux_virtdisk_handler.cpp"],
    hdrs = ["linux_virtdisk_handler.h"],
    visibility = ["//visibility:public"]
)